version: 0.2

phases:
  pre_build:
    commands:
      - echo Deployment started on 'date'
      - echo Syncing S3 Content
      - aws s3 sync ./build/ s3://invest-valid
  build:
    commands:
      - echo Invalidating CloudFront Cache
  post_build:
    commands:
      - echo Deployment completed on 'date'