version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 10 
    commands:
      - echo install awscli
      - pip install awscli
  pre_build:
    commands:
      - echo build resources
      - npm install
      - npm run build
      - echo Deployment started on 'date'
      - echo Syncing S3 Content
      - aws s3 sync ./build/ s3://investvalid.com
  build:
    commands:
      - echo Invalidating CloudFront Cache
      - aws cloudfront create-invalidation --distribution-id E9NYMX5OU7BWC --paths "/*"
  post_build:
    commands:
      - echo Deployment completed on 'date'